version: '3.8'

services:
  users-ms:
    build: ./services/users-ms
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - ./env/.env

  academic-ms:
    build: ./services/academic-ms
    ports:
      - "8082:8082"
    environment:
      - ACADEMIC_PORT=8082
      - DB_HOST=${DB_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - ./env/.env

  student-and-enrollment-ms:
    build: ./services/student-and-enrollment-ms
    ports:
      - "8083:8083"
    environment:
      - STUDENT_PORT=8083
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - ./env/.env

  billing-ms:
    build: ./services/billing-ms
    ports:
      - "8084:8084"
    environment:
      - BILLING_PORT=8084
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - ./env/.env

  gateway-ms:
    build: ./services/gateway-ms
    ports:
      - "8080:8080"
    environment:
      - GATEWAY_PORT=8080
      # CONFIGURADO: IP Tailscale de cada maquina
      - USERS_MS_URL=${USERS_MS_URL:-http://100.125.236.96:8081}
      - ACADEMIC_MS_URL=${ACADEMIC_MS_URL:-http://100.91.4.45:8082}
      - STUDENT_MS_URL=${STUDENT_MS_URL:-http://100.105.17.78:8083}
      - BILLING_MS_URL=${BILLING_MS_URL:-http://100.119.91.28:8084}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - ./env/.env
