version: '3.8'

services:
  users-ms:
    image: vanguard12s/users-ms:lab
    ports:
      - "8081:8081"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      - SERVER_PORT=8081
      - DB_HOST=34.68.197.98
      - DB_WRITE_HOST=34.68.197.98
      - DB_WRITE_PORT=5000
    env_file:
      - ../env/.env
    networks:
      - vanguard-net

  academic-ms:
    image: vanguard12s/academic-ms:lab
    ports:
      - "8082:8082"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      - ACADEMIC_PORT=8082
      - DB_HOST=34.68.197.98
      - DB_WRITE_HOST=34.68.197.98
      - DB_WRITE_PORT=5000
      - DB_READ_HOST=34.68.197.98
      - DB_READ_PORT=5001
      - REDIS_HOST=vps.wissegt.com
      - REDIS_PORT=6379
    env_file:
      - ../env/.env
    networks:
      - vanguard-net

  student-and-enrollment-ms:
    image: vanguard12s/student-and-enrollment-ms:lab
    ports:
      - "8083:8083"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      - STUDENT_PORT=8083
      - DB_HOST=34.68.197.98
      - DB_WRITE_HOST=34.68.197.98
      - DB_WRITE_PORT=5000
    env_file:
      - ../env/.env
    networks:
      - vanguard-net

  billing-ms:
    image: vanguard12s/billing-ms:lab
    ports:
      - "8084:8084"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      - BILLING_PORT=8084
      - DB_HOST=34.68.197.98
      - DB_WRITE_HOST=34.68.197.98
      - DB_WRITE_PORT=5000
    env_file:
      - ../env/.env
    networks:
      - vanguard-net

  gateway-ms:
    image: vanguard12s/gateway-ms:lab
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      - GATEWAY_PORT=8080
      - USERS_MS_URL=http://users-ms:8081
      - ACADEMIC_MS_URL=http://academic-ms:8082
      - STUDENT_MS_URL=http://student-and-enrollment-ms:8083
      - BILLING_MS_URL=http://billing-ms:8084
      - REDIS_HOST=vps.wissegt.com
      - REDIS_PORT=6379
    env_file:
      - ../env/.env
    networks:
      - vanguard-net

  chaos-proxy:
    image: vanguard12s/chaos-proxy:real-v1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - vanguard-net

  api-proxy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    command: caddy reverse-proxy --from api.wissegt.com --to gateway-ms:8080
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - vanguard-net

networks:
  vanguard-net:
    driver: overlay

volumes:
  caddy_data:
  caddy_config:
