global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'vanguard-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - 'users-ms:8081'
        - 'academic-ms:8082'
        - 'student-and-enrollment-ms:8083'
        - 'billing-ms:8084'
        - 'gateway-ms:8080'
