global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - '104.197.126.0:80'

  - job_name: 'users-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - '104.197.126.0:8081'

  - job_name: 'academic-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - '104.197.126.0:8082'

  - job_name: 'student-and-enrollment-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - '104.197.126.0:8083'

  - job_name: 'billing-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - '104.197.126.0:8084'
