global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'vanguard-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        # CAMBIO REQUERIDO: Reemplazar con IP Tailscale de USERS
        - '127.0.0.1:8081' 
        # CAMBIO REQUERIDO: Reemplazar con IP Tailscale de ACADEMIC
        - '127.0.0.1:8082'
        # CAMBIO REQUERIDO: Reemplazar con IP Tailscale de STUDENT
        - '127.0.0.1:8083'
        # CONFIGURADO: IP Tailscale de BILLING
        - '100.119.91.28:8084'
        # CONFIGURADO: IP Tailscale de GATEWAY (Esta Maquina)
        - '100.70.253.58:8080'
