services:
  # Nodo Principal
  pg-master:
    image: bitnami/postgresql:latest
    container_name: pg-master
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user_svc
      - POSTGRESQL_REPLICATION_PASSWORD=Kj82_mP91_Xz77_Rt
      - POSTGRESQL_USERNAME=bd2equipomari
      - POSTGRESQL_PASSWORD=Kj82_mP91_Xz77_Rt
      - POSTGRESQL_DATABASE=bdedu
    volumes:
      - ./master_data:/bitnami/postgresql

  # Nodo Replica
  pg-replica:
    image: bitnami/postgresql:latest
    container_name: pg-replica
    restart: always
    depends_on:
      - pg-master
    ports:
      - "5433:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=pg-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=repl_user_svc
      - POSTGRESQL_REPLICATION_PASSWORD=Kj82_mP91_Xz77_Rt
      - POSTGRESQL_MASTER_USER=bd2equipomari
      - POSTGRESQL_MASTER_PASSWORD=Kj82_mP91_Xz77_Rt
      - POSTGRESQL_PASSWORD=Kj82_mP91_Xz77_Rt
    volumes:
      - ./replica_data:/bitnami/postgresql

  # Cache
  redis-cache:
    image: bitnami/redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=Kj82_mP91_Xz77_Rt
    volumes:
      - ./redis_data:/bitnami/redis

  # Mensajeria
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=vanguard_user
      - RABBITMQ_DEFAULT_PASS=Kj82_mP91_Xz77_Rt

  # Monitoreo - Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus

  # Monitoreo - Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
